[package]
name = "bismit"
version = "0.0.1"
authors = ["Nick Sanders <github.com/c0gent>"]

[dependencies]
bitflags = "*"
rand = "*"
num = "*"
libc = "*"
enum_primitive = "*"
find_folder = "*"
# ocl = "0.2"
time = "*"

[dependencies.microcosm]
git = "https://github.com/cogciprocate/microcosm.git"

[dependencies.ocl]
git = "https://github.com/cogciprocate/ocl_rust.git"
# path = "/home/nick/projects/ocl"

# [dependencies.time]
# git = "https://github.com/rust-lang/time.git"

# [dependencies.bitflags]
# git = "https://github.com/rust-lang-nursery/bitflags.git"
