[package]
name = "bismit"
version = "0.0.1"
authors = ["Nick Sanders <github.com/c0gent>"]

[features]
profile = ["cpuprofiler"]

[dependencies.ocl]
version = "*"
path = "../ocl/ocl"
# git = "https://github.com/cogciprocate/ocl.git"
# features = ["kernel_debug_sleep", "kernel_debug_print"]
# features = ["kernel_debug_print"]

[dependencies]
bitflags = "*"
rand = "*"
num = "*"
libc = "*"
enum_primitive = "*"
find_folder = "*"
time = "*"
twox-hash = "*"
colorify = "*"
futures = "*"
futures-cpupool = "*"
tokio-core = "*"
crossbeam = "*"
cpuprofiler = { version = "*", optional = true }
# log = "*"

[workspace]
members = ["eval"]

[replace]
# "qutex:0.1.1" = { git = "https://github.com/cogciprocate/qutex" }
# "qutex:0.1.1" = { path = "/home/nick/src/github.com/cogciprocate/qutex" }
# "cl-sys:0.3.0" = { git = 'https://github.com/cogciprocate/cl-sys' }
# "ocl-core:0.5.1" = { git = "https://github.com/cogciprocate/ocl-core" }
# "ocl-core:0.3.2" = { path = "/home/nick/src/github.com/cogciprocate/ocl-core" }
# "ocl-core:0.3.2" = { path = "../ocl-core" }