[package]
name = "bismit"
version = "0.0.1"
authors = ["Nick Sanders <github.com/nsan1129>"]

[dependencies]
bitflags = "0.3"
rand = "0.3"
num = "0.1"
libc = "0.1"
enum_primitive = "0.1"
ocl = "0.1"

[dependencies.microcosm]
git = "https://github.com/cogciprocate/microcosm.git"

#[dependencies.ocl]
#git = "https://github.com/cogciprocate/ocl_rust.git"
#path = "/home/nick/projects/ocl"

[dependencies.time]
git = "https://github.com/rust-lang/time.git"

#[dependencies.bitflags]
#git = "https://github.com/rust-lang/bitflags.git"


# Comment



