[package]
name = "bismit"
version = "0.0.1"
authors = ["Nick Sanders <github.com/nsan1129>"]

[dependencies]
bitflags = "0.1.1"
rand = "0.3.5"
num = "0.1.19"
libc = "0.1.5"

[dependencies.microcosm]
git = "https://github.com/cogciprocate/microcosm.git"

[dependencies.time]
git = "https://github.com/rust-lang/time.git"

#[dependencies.bitflags]
#git = "https://github.com/rust-lang/bitflags.git"



# Comment
# 


