[package]
name = "bismit"
version = "0.0.1"
authors = ["Nick Sanders <github.com/c0gent>"]

# [dependencies.microcosm]
# git = "https://github.com/cogciprocate/microcosm.git"

# [dependencies.time]
# git = "https://github.com/rust-lang/time.git"

# [dependencies.bitflags]
# git = "https://github.com/rust-lang-nursery/bitflags.git"

# [dependencies.ocl]
# path = "/home/nick/projects/ocl"
# git = "https://github.com/cogciprocate/ocl.git"
# features = ["kernel_debug_sleep", "kernel_debug_print"]
# features = ["kernel_debug_print"]

[dependencies]
ocl = "*"
# ocl = { path = "/home/nick/projects/ocl", version = "0.11" }
# ocl = { path = "/home/nick/projects/ocl" }
# ocl = { path = "../ocl" }
# ocl = { version = "0.12.0", git = "https://github.com/cogciprocate/ocl" }
bitflags = "*"
rand = "*"
num = "*"
libc = "*"
enum_primitive = "*"
find_folder = "*"
time = "*"
twox-hash = "*"
colorify = "*"
futures = "*"
tokio-core = "*"

[workspace]
members = ["eval"]


# [dev-dependencies]

# [replace]
# "cl-sys:0.1.0" = { git = 'https://github.com/cogciprocate/cl-sys' }
# "ocl-core:0.3.2" = { git = "https://github.com/cogciprocate/ocl-core" }
# "ocl-core:0.3.2" = { path = "/home/nick/src/github.com/cogciprocate/ocl-core" }
# "ocl-core:0.3.2" = { path = "../ocl-core" }