[package]
name = "bismit"
version = "0.0.1"
authors = ["Nick Sanders <github.com/c0gent>"]

# [dependencies.microcosm]
# git = "https://github.com/cogciprocate/microcosm.git"

# [dependencies.time]
# git = "https://github.com/rust-lang/time.git"

# [dependencies.bitflags]
# git = "https://github.com/rust-lang-nursery/bitflags.git"

[dependencies.ocl]
path = "/home/nick/projects/ocl"
# git = "https://github.com/cogciprocate/ocl.git"
# features = ["kernel_debug_sleep", "kernel_debug_print"]
# features = ["kernel_debug_print"]

# [replace]
# "cl-sys:0.1.0" = { git = 'https://github.com/cogciprocate/cl-sys' }
# "ocl-core:0.1.0" = { git = "https://github.com/cogciprocate/ocl-core" }

[dependencies]
# ocl = "*"
bitflags = "*"
rand = "*"
num = "*"
libc = "*"
enum_primitive = "*"
find_folder = "*"
time = "*"
twox-hash = "*"
colorify = "*"


[replace]
"ocl-core:0.2.3" = { git = "https://github.com/cogciprocate/ocl-core" }