[package]
name = "eval"
version = "0.0.1"
authors = ["Nick Sanders <cogciprocate@gmail.com>"]

[dependencies]
vibi = { path = "../../vibi" }
rand = "*"
log = "*"
env_logger = "*"
clap = "*"
colorify = "*"