[package]
name = "example_vibi-motor"
version = "0.0.1"
authors = ["Nick Sanders <nsan1129@gmail.com>"]

[dependencies]
vibi = { path = "/home/nick/src/github.com/cogciprocate/vibi" }
lazy_static = "*"